### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by chenweiqian** [Spenstar/Review-King#1]
when i wanted use the add function, i met the problem. I don't know why.
And When I create app according to the tutorial，I also met the problem too！
If you know how to fix it，could you help me？Thanks！！
How do you create reviewing database?I suspect that this may be the reason.

The details about the problem as belows：
TypeError: Cannot read property 'push' of undefined
    at ModalImpl._onDidDismiss (http://localhost:8100/build/main.js:85:31)
    at ModalImpl.ViewController._willUnload (http://localhost:8100/build/vendor.js:19039:36)
    at OverlayPortal.NavControllerBase._willUnload (http://localhost:8100/build/vendor.js:49089:18)
    at OverlayPortal.NavControllerBase._cleanup (http://localhost:8100/build/vendor.js:48991:26)
    at OverlayPortal.NavControllerBase._transitionFinish (http://localhost:8100/build/vendor.js:48890:18)
    at http://localhost:8100/build/vendor.js:48870:26
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4982:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)

**Comment by Spenstar** [comment]
Wow, I haven't looked at this project for a while. The bug should be fixed now by #2. In a nutshell, the `reviews` variable was not being initialized as an array, causing the `.push()` function to not know what to do.

**Comment by chenweiqian** [comment]
Thanks！！ @Spenstar
